//
//  Data.swift
//  UISearchControllerDemoSimple
//
//  Created by Jonas Reinsch on 28.01.16.
//  Copyright © 2016 Jonas Reinsch. All rights reserved.
//

import Foundation

let cities = [
    "Amsterdam",
    "Athens",
    "Bogota",
    "Bombay",
    "Brussels",
    "Buenos",
    "Cairo",
    "Caracas",
    "Chicago",
    "Copenhagen",
    "Dublin",
    "Dusseldorf",
    "Frankfurt",
    "Geneva",
    "Helsinki",
    "Hong",
    "Houston",
    "Jakarta",
    "Johannesburg",
    "Kuala",
    "Lagos",
    "Lisbon",
    "London",
    "Los Angeles",
    "Luxembourg",
    "Madrid",
    "Manila",
    "Mexico",
    "Milan",
    "Montreal",
    "Nairobi",
    "New York",
    "Nicosia",
    "Nairobi",
    "New York",
    "Nicosia",
    "Nairobi",
    "New York",
    "Nicosia",
    "Nairobi",
    "New York",
    "Nicosia",
    "Nairobi",
    "New York",
    "Nicosia",
    "Nairobi",
    "New York",
    "Nicosia",
    "Nairobi",
    "New York",
    "Nicosia",
    "Nairobi",
    "New York",
    "Nicosia",
    "Nairobi",
    "New York",
    "Nicosia",
    "Oslo",
    "Panama",
    "Paris",
    "Rio",
    "Sao Paulo",
    "Seoul",
    "Singpore",
    "Stockholm",
    "Sydney",
    "Taipei",
    "Tel",
    "Tokyo",
    "Toronto",
    "Vienna",
    "Zurich"]
